remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "No Small Feat: Whuppin' AI"
description: "Rules & Information for the Fall 2023 ASS Contest"
